strip = neopixel.create(DigitalPin.P1, 24, NeoPixelMode.RGB)

def on_forever():
    strip.show_color(neopixel.colors(NeoPixelColors.BLACK))
    basic.pause(600)
    strip.show_color(neopixel.colors(NeoPixelColors.YELLOW))
    basic.pause(600)
    strip.show_color(neopixel.colors(NeoPixelColors.GREEN))
    basic.pause(600)
    strip.show_color(neopixel.colors(NeoPixelColors.BLUE))
    basic.pause(600)
    strip.show_color(neopixel.colors(NeoPixelColors.VIOLET))
    basic.pause(400)
    strip.show_color(neopixel.colors(NeoPixelColors.PURPLE))
    basic.pause(400)
    strip.show_color(neopixel.colors(NeoPixelColors.ORANGE))
    basic.pause(400)
    strip.show_color(neopixel.colors(NeoPixelColors.RED))
    basic.pause(400)
    for index in range(4):
        strip.show_rainbow(1, 360)
        basic.pause(200)
        strip.show_color(neopixel.colors(NeoPixelColors.BLACK))
        basic.pause(200)
    strip.show_color(neopixel.colors(NeoPixelColors.YELLOW))
    basic.pause(1600)
    for index2 in range(3):
        strip.show_color(neopixel.colors(NeoPixelColors.ORANGE))
        basic.pause(200)
        strip.show_color(neopixel.colors(NeoPixelColors.WHITE))
        basic.pause(200)
    strip.show_color(neopixel.colors(NeoPixelColors.ORANGE))
    basic.pause(500)
    strip.show_color(neopixel.colors(NeoPixelColors.YELLOW))
    basic.pause(500)
    strip.show_color(neopixel.colors(NeoPixelColors.RED))
    basic.pause(500)
    strip.show_color(neopixel.colors(NeoPixelColors.VIOLET))
    basic.pause(1000)
    strip.show_color(neopixel.colors(NeoPixelColors.BLACK))
    basic.pause(3600)
    for index3 in range(12):
        strip.show_color(neopixel.colors(NeoPixelColors.BLUE))
        basic.pause(200)
        strip.show_color(neopixel.colors(NeoPixelColors.INDIGO))
        basic.pause(200)
    strip.show_color(neopixel.colors(NeoPixelColors.WHITE))
    basic.pause(1000)
    strip.show_color(neopixel.colors(NeoPixelColors.ORANGE))
    basic.pause(500)
basic.forever(on_forever)
