let strip = neopixel.create(DigitalPin.P1, 24, NeoPixelMode.RGB)
basic.forever(function () {
    basic.pause(600)
    strip.showColor(neopixel.colors(NeoPixelColors.Yellow))
    basic.pause(600)
    strip.showColor(neopixel.colors(NeoPixelColors.Green))
    basic.pause(600)
    strip.showColor(neopixel.colors(NeoPixelColors.Blue))
    basic.pause(600)
    strip.showColor(neopixel.colors(NeoPixelColors.Violet))
    basic.pause(400)
    strip.showColor(neopixel.colors(NeoPixelColors.Purple))
    strip.showColor(neopixel.colors(NeoPixelColors.Orange))
    basic.pause(400)
    strip.showColor(neopixel.colors(NeoPixelColors.Red))
    basic.pause(400)
    for (let index = 0; index < 4; index++) {
        strip.showRainbow(1, 360)
        basic.pause(200)
        strip.showColor(neopixel.colors(NeoPixelColors.White))
        basic.pause(200)
    }
    strip.showColor(neopixel.colors(NeoPixelColors.Yellow))
    basic.pause(1600)
    for (let index = 0; index < 3; index++) {
        strip.showColor(neopixel.colors(NeoPixelColors.Orange))
        basic.pause(200)
        strip.showColor(neopixel.colors(NeoPixelColors.White))
        basic.pause(200)
    }
})
