let strip = neopixel.create(DigitalPin.P0, 24, NeoPixelMode.RGB)
basic.forever(function () {
    basic.pause(300)
    strip.showColor(neopixel.colors(NeoPixelColors.Yellow))
    basic.pause(800)
    strip.showColor(neopixel.colors(NeoPixelColors.Green))
    basic.pause(800)
    strip.showColor(neopixel.colors(NeoPixelColors.Blue))
    basic.pause(800)
    strip.showColor(neopixel.colors(NeoPixelColors.Purple))
    basic.pause(800)
    strip.showColor(neopixel.colors(NeoPixelColors.Violet))
    basic.pause(300)
    strip.showColor(neopixel.colors(NeoPixelColors.Orange))
    basic.pause(300)
    strip.showColor(neopixel.colors(NeoPixelColors.Red))
    basic.pause(300)
    strip.showRainbow(1, 360)
    basic.pause(1500)
    strip.showColor(neopixel.colors(NeoPixelColors.Yellow))
    basic.pause(1500)
    strip.showColor(neopixel.colors(NeoPixelColors.Orange))
    basic.pause(200)
    strip.showColor(neopixel.colors(NeoPixelColors.White))
    basic.pause(200)
    strip.showColor(neopixel.colors(NeoPixelColors.Orange))
    basic.pause(200)
    strip.showColor(neopixel.colors(NeoPixelColors.White))
    basic.pause(200)
    strip.showColor(neopixel.colors(NeoPixelColors.Orange))
    basic.pause(200)
    strip.showColor(neopixel.colors(NeoPixelColors.Orange))
    basic.pause(200)
    strip.showColor(neopixel.colors(NeoPixelColors.White))
    basic.pause(200)
    strip.showColor(neopixel.colors(NeoPixelColors.Orange))
    basic.pause(200)
})
basic.forever(function () {
	
})
